import type { Metadata } from "next";
import "@/app/globals.css";
import React from "react";
import AdminPanelLayout from "@/components/dashboard/layout";

export const metadata: Metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AdminPanelLayout>{children}</AdminPanelLayout>
      </body>
    </html>
  );
}
